In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('Video Game Sales.csv')
df['Total_Sales'] = df['NA_Sales'] + df['EU_Sales'] + df['JP_Sales'] + df['Other_Sales']

avg_year = df['Year'].mean()
old_games = df[df['Year'] < avg_year]
new_games = df[df['Year'] >= avg_year]

old_mode = old_games['Publisher'].mode()[0]
new_mode = new_games['Publisher'].mode()[0]
old_gmode = old_games['Genre'].mode()[0]
new_gmode = new_games['Genre'].mode()[0]

print(f"Average Year: {avg_year:.0f}")
print(f" Old Games Mode Publisher: {old_mode}")
print(f" New Games Mode Publisher: {new_mode}")
print(f" Old Games Mode Genre: {old_gmode}")
print(f" New Games Mode Genre: {new_gmode}")

nintendo_role_playing_games = df[(df["Publisher"] == 'Nintendo') & (df['Genre'] == 'Role-Playing')]
count_nrpg = len(nintendo_role_playing_games)
print(f"Number of Nintendo of Role-Playing games: {count_nrpg}")

top_5_nrpg = nintendo_role_playing_games.sort_values(by='Total_Sales', ascending=False).head(5)
print("\nTop 5 Nintendo Role-Playing games by sales:")
display(top_5_nrpg[['Name', 'Publisher', 'Genre', 'Total_Sales']])

activision_shooters = df[(df['Year'] >= avg_year) &  (df['Publisher'] == 'Activision') & (df['Genre'] == 'Shooter')]
count_activision_shooters = len(activision_shooters)
print(f"Total new Activision Shooter games: {count_activision_shooters}")

top_5_activision_shooters = activision_shooters.sort_values(by='Total_Sales', ascending=False).head(5)

top_5_activision_shooters[['Name', 'Publisher', 'Genre', 'Year', 'Total_Sales']]

def run_simulation(df, x, n=50):
    count = 0
    for i in range(n):
        sample = df.sample(n=x, replace=False)
        if(sample['NA_Sales'] > 3).all():
            count += 1

    p_hat = count / n
    return p_hat

def theoretical_prob(df, x):
    N = len(df)
    K = (df['NA_Sales'] > 3).sum()

    if K < x:
        return 0.0

    p = 1.0
    for i in range(x):
        p *= (K - i)/(N - i)
    return p

p_hat = run_simulation(df, x=7, n=50)
p = theoretical_prob(df, 7)

print(f"Simulated Probability (p_hat): {p_hat}")
print(f"Theoretical Probability (p): {p:.6f}")

def optimization(df, x, n):
    p_hat = run_simulation(df, x=x, n=n)
    p = theoretical_prob(df, x)
    score = (n ** 2) + 1000 * abs(p_hat - p)

    return score

for n_test in [5, 10, 15, 20, 30]:
    score = optimization(df, x=7, n=n_test)
    print(f"n = {n_test:2d} | F(X) = {score:.4f}")

df.head()

Average Year: 2005
 Old Games Mode Publisher: Nintendo
 New Games Mode Publisher: Nintendo
 Old Games Mode Genre: Platform
 New Games Mode Genre: Shooter
Number of Nintendo of Role-Playing games: 11

Top 5 Nintendo Role-Playing games by sales:

                             Name Publisher         Genre  Total_Sales
4        Pokemon Red/Pokemon Blue  Nintendo  Role-Playing        31.38
12    Pokemon Gold/Pokemon Silver  Nintendo  Role-Playing        23.09
20  Pokemon Diamond/Pokemon Pearl  Nintendo  Role-Playing        18.35
25  Pokemon Ruby/Pokemon Sapphire  Nintendo  Role-Playing        15.84
26    Pokemon Black/Pokemon White  Nintendo  Role-Playing        15.32

Total new Activision Shooter games: 14
Simulated Probability (p_hat): 0.44
Theoretical Probability (p): 0.308345
n =  5 | F(X) = 133.3447
n = 10 | F(X) = 208.3447
n = 15 | F(X) = 316.6553
n = 20 | F(X) = 558.3447
n = 30 | F(X) = 975.0114

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Total_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.83
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.38